### ISSUE TITLE
GPU requirements

### ISSUE THREAD

**Issue by mariainescravo** [dicarlolab/vonenet#18]
Hi! Thank you so much for releasing the code!

If I wanted to train the VOneResNet50 on a NVIDIA GeForce RTX 2070 how long should I expect it to take? I'm new to training neural networks this big and am working on a small project for a course, so it would be good to have an estimate.

Thank you so much!

Maria Inês

**Comment by tiagogmarques** [comment]
Hi Maria Inês,

Thank you for your interest!

I don't know about that particular GPU but you can have an estimate by starting the training with the largest batch that you can fit in the GPU and see how long it takes to run each batch. The standard models were trained with 70 batches. This usually takes around 5 days on a NVIDIA Quadro RTX 6000 https://www.nvidia.com/en-us/design-visualization/quadro/rtx-6000/

Unless you want to make modifications to the base network, you can use the pre-trained model weights that we provide.

Best,
Tiago

**Comment by ALLIESXO** [comment]
@mariainescravo 
If you need to train the network on your own graphic card you can also use the imagenette dataset which works out of the box with this repository.
A complete training using imagenette took approx. 3 hours on RTX 2070S.

**Comment by mariainescravo** [comment]
Ah thanks, will try that!

**Comment by tiagogmarques** [comment]
The Imagenette dataset is usually used at 160px resolution so you'll need to update the preprocessing in the DataLoader on train.py (lines 289 and 339-340). 

Also the standard parameters of the VOneBlock that are used to generate the Gabor Filter Bank were designed to work with 224px input images. One easy adaption is just to change the visual_degrees from 8 to 6 which you can pass as an argument when running train.py or change the value on line 47).

I cover a bit the importance of estimating the input size in visual degrees for different datasets (such as CIFAR or MNIST) on a small tutorial that is available online:
https://www.youtube.com/watch?v=PpsIyLk9yZg
