### ISSUE TITLE
ny_dist_marg has Nan values

### ISSUE THREAD

**Issue by code-Assasin** [dicarlolab/vonenet#19]
The ny_dist_marg matrix in the params.py file seems to have nan values making gradient computation impossible. Please check?

**Comment by tiagogmarques** [comment]
That matrix is only used to generate the Gabor Filter Bank kernels which have finite values. No gradients are passed through the marginal distribution of ny.

On Aug 20, 2021, at 3:22 PM, Harshitha Machiraju ***@***.***> wrote:

﻿

The ny_dist_marg matrix in the params.py file seems to have nan values making gradient computation impossible. Please check?

**Comment by code-Assasin** [comment]
The fixed matrix(no gradient computation) itself seems to contain nans : 

<img width="538" alt="Screenshot 2021-08-25 at 10 17 41" src="https://user-images.githubusercontent.com/15107872/130754374-4e261d38-b403-487e-afcf-174a195cc3e6.png">

**Comment by tiagogmarques** [comment]
Again, no gradients are passed through these distributions. They are not used during model training, inference and attack. They are used to instantiate the nx and ny arrays which in turn are used to create the Gabor Filter Bank (GFB) weights during the model initialization. The GFB weights do not contain any nans.
