### ISSUE TITLE
k_exc parameter

### ISSUE THREAD

**Issue by normster** [dicarlolab/vonenet#5]
Hi,

Thanks for releasing your code! Quick question- what is the significance of the k_exc parameter used in the V1 block?

https://github.com/dicarlolab/vonenet/blob/master/vonenet/modules.py#L91

Norman

**Comment by tiagogmarques** [comment]
Hi Norman,

k_exc is just a scaling factor for the outputs of the Gabors. 
All the models included in the repo were trained with k_exc=25

Let me know if you have more questions.

Cheers,
Tiago

---
Tiago Marques
Postdoctoral Researcher
MIT Department of Brain and Cognitive Sciences
PhRMA Foundation Fellow

**Comment by normster** [comment]
Thanks for the response! How was this value chosen? Does it intentionally match the Gabor filter kernel size?

**Comment by tiagogmarques** [comment]
The value was chosen such that mean activation for an ImageNet image are approximately 1. It has nothing to do with the kernel size.

---
Tiago Marques
Postdoctoral Researcher
MIT Department of Brain and Cognitive Sciences
PhRMA Foundation Fellow

**Comment by normster** [comment]
Gotcha, thanks!
