### ISSUE TITLE
explaining neural variances

### ISSUE THREAD

**Issue by bsvineethiitg** [dicarlolab/vonenet#7]
Thank you for the code for the V1Block. Interesting work!

I was wondering how you exactly compared regular convolutional features and the ones from VOneNet to explain the Neural Variances. 

Since the paper stresses that this model is SoTA in explaining these, I would be really glad if you can include the code for that too / or if you could point me to existing repositories that do that (if you are aware of any), that'd be great too!

Thanks again!

**Comment by tiagogmarques** [comment]
Glad you enjoyed our work!

The VOneNet is implemented exactly like any other regular CNN so the procedure to evaluate the neuronal explained variance was the same.

We used the Brain-Score platform to evaluate the V1 explained variance of the VOneBlock and the other models.
http://www.brain-score.org

All code is available at:
https://github.com/brain-score

Particularly, code for the V1 neuronal dataset are inside the brain-score package:
https://github.com/brain-score/brain-score

The V1 dataset was first used in the following study:
Freeman, J., Ziemba, C. M., Heeger, D. J., Simoncelli, E. P. & Movshon, J. A. A functional and perceptual signature of the second visual area in primates. Nat. Neurosci. 16, 974–981 (2013).
