### ISSUE TITLE
Can you provide the trained VOneNet model file onto google drive?

### ISSUE THREAD

**Issue by machanic** [dicarlolab/vonenet#8]
Can you provide the trained VOneNet model file onto google drive so that I can download for my experiments.
CIFAR-10, CIFAR-100, ImageNet datasets, do you have the trained model file??

**Comment by tiagogmarques** [comment]
Does it need to be on a google drive? The links to the model weights are available on the readme and you can also download the weights with the code. For example, the link to the VOneResNet50 model is:
https://vonenet-models.s3.us-east-2.amazonaws.com/voneresnet50_e70.pth.tar

All the results in our paper are on ImageNet and the models refer to this. However, we are planning to do some future experiments with CIFAR and will include the models for it.

**Comment by machanic** [comment]
OK thank you, I need to add experiments on it? Do you have only the CIFAR-10 trained model? Do you have ImageNet and CIFAR-100 model?

**Comment by machanic** [comment]
Thank you, if you have trained on CIFAR-10 and CIFAR-100 , please notify me. It will be quick, because the image and dataset is very small compared with ImageNet.
